/* Plain-text summaries patients can copy and share with their clinician. */

const pct = (v) => `${(Math.max(0, Math.min(1, Number(v) || 0)) * 100).toFixed(1)}%`;
const stamp = () => new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' });
const foot = () =>
  'Generated by MediDiagnose (informational only — not a diagnosis). Confirm with a qualified clinician.';

export function buildImageSummary(result, fileName) {
  const r = result || {};
  const p = r.prediction || {};
  const lines = [
    `MEDIDIAGNOSE — IMAGE ANALYSIS · ${stamp()}`,
    fileName ? `File: ${fileName}` : null,
    `Condition: ${p.name || 'Unknown'}${p.type ? ` (${p.type})` : ''}`,
    `Severity: ${r.severity || 'unknown'} · Confidence: ${pct(p.confidence)}`,
  ];
  if (Array.isArray(r.all_predictions) && r.all_predictions.length > 1) {
    lines.push('', 'Ranked possibilities:');
    r.all_predictions
      .slice(0, 5)
      .forEach((x, i) => lines.push(`  ${i + 1}. ${x.name} — ${pct(x.confidence)}`));
  }
  if (r.urgency?.timeline) lines.push('', `Urgency: ${r.urgency.timeline} — ${r.urgency.action || ''}`.trim());
  const rec = r.recommendations;
  if (rec?.message) lines.push('', rec.title || 'Guidance', rec.message);
  if (Array.isArray(rec?.actions) && rec.actions.length) {
    lines.push('Actions:');
    rec.actions.forEach((a) => lines.push(`  - ${a}`));
  }
  if (Array.isArray(rec?.warning_signs) && rec.warning_signs.length) {
    lines.push('Warning signs (seek care if these appear):');
    rec.warning_signs.forEach((w) => lines.push(`  ! ${w}`));
  }
  lines.push('', foot());
  return lines.filter((l) => l !== null).join('\n');
}

export function buildSymptomSummary(result, symptomLabels = []) {
  const r = result || {};
  const lines = [
    `MEDIDIAGNOSE — SYMPTOM ASSESSMENT · ${stamp()}`,
    symptomLabels.length ? `Symptoms: ${symptomLabels.join(', ')}` : null,
    `Predicted condition: ${typeof r.prediction === 'string' ? r.prediction : r.prediction?.disease || 'Unknown'}`,
    `Confidence: ${pct(r.confidence)} (${r.confidence_tier || 'n/a'})`,
  ];
  if (r.description) lines.push('', r.description);
  if (Array.isArray(r.alternative_diagnoses) && r.alternative_diagnoses.length) {
    lines.push('', 'Also considered:');
    r.alternative_diagnoses
      .slice(0, 4)
      .forEach((a) => lines.push(`  - ${a.disease} — ${pct(a.confidence)}`));
  }
  const tips = [...(r.recommendations || []), ...(r.precautions || [])];
  if (tips.length) {
    lines.push('', 'Guidance:');
    tips.slice(0, 8).forEach((t) => lines.push(`  - ${t}`));
  }
  lines.push('', foot());
  return lines.filter((l) => l !== null).join('\n');
}

export function buildScreeningSummary(kind, result) {
  const r = result || {};
  const isHeart = kind === 'heart';
  const title = isHeart ? 'HEART RISK SCREENING' : 'BREAST CANCER SCREENING';
  const headline = isHeart
    ? `Risk level: ${r.risk_level || r.prediction || 'Unknown'} (probability ${pct(r.probability)})`
    : `Prediction: ${r.prediction || 'Unknown'} (malignancy probability ${pct(r.probability)}, model confidence ${pct(r.confidence)})`;
  const lines = [`MEDIDIAGNOSE — ${title} · ${stamp()}`, headline];
  if (r.recommendation?.message) lines.push('', r.recommendation.message);
  if (Array.isArray(r.recommendation?.actions) && r.recommendation.actions.length) {
    lines.push('Recommended:');
    r.recommendation.actions.forEach((a) => lines.push(`  - ${a}`));
  }
  lines.push('', foot());
  return lines.join('\n');
}
